### ISSUE TITLE
Mesh Networks as a tactical avoidance of ISPs

### ISSUE THREAD

**Issue by bfost1** [nniiicc/faculty_homepage#6]
I am interested in this project because it seems to be an interesting resource. I am unfamiliar with Mesh networks and it gives me another opportunity to learn something new and another possibility for exploring another field of study. The relationship between net neutrality, mesh networks and ISPs. This also brings up government regulations and control and community. People are creatively searching for ways to still have the freedom to search the internet without having restrictions on the content that they want to view. If FCC regulations for net neutrality are safe, for now, how popular do these networks continue to become? Could this be a movement that could rival large corporations for DIY ISPs? Could this be similar to how streaming services have competed with cable television services where people have created an à la carte viewing experience that is more cost effective and meaningful? I can devote 5-10+ hours per week for the next two quarters. I am available to meet with you via videoconferencing 11/5-7 between the hours of 8AM - 6PM PST. My email address is

**Comment by nniiicc** [comment]
Below are some additional resources focused on the topic of wifi hotspot lending: 

- https://www.libraryjournal.com/?detailStory=hot-spot-techknowledge (also see resources they link at the bottom of the page) 
- https://citiesspeak.org/2015/06/11/why-city-libraries-are-lending-wifi-hotspots-to-low-income-residents/ 
- https://www.tsl.texas.gov/ld/librarydevelopments/?p=21014
- http://sites.utexas.edu/imlsedgesgrant/ 

More about mesh networks and libraries: 
- https://www.imls.gov/blog/2016/10/libraries-leading-equitable-digital-access-and-connectivity
- http://publiclibrariesonline.org/2018/03/towards-a-framework-for-digital-justice-in-public-libraries/
