### ISSUE TITLE
Digital Badges

### ISSUE THREAD

**Issue by katedelr** [nniiicc/faculty_homepage#7]
@nniiicc 
My interest in the Digital Badges research project is both professional and personal. In my work life, I am a Content Editor and Curator for the App Store at Apple, mainly focusing on digital games for iOS. Personally, I am an avid gamer and especially enjoy RPGs (very badge/achievement heavy). I also utilize other means of gamifying my life, such as Habitica (https://habitica.com) to manage my productivity. In all of these endeavors, I've noticed my own propensity toward attaining achievement badges and have also been part of workplace discussions involving applications of such badges for training and/or employee education purposes.

Having taken a brief look at the resources from Wikipedia, I am especially interested in pursuing this research project to see how and when digital badges to fail or succeed. If/when they're successful in virtual spaces (such as gaming), how have they then been applied to real-world scenarios like education (through the MacArthur Foundation, for example) or in the workplace? What are the challenges toward bringing badges into these settings (trusted sourcing/authorities, open vs digital badges, self reporting and accountability)?

I can devote likely 10-15+ hours/quarter over the next two quarters to this project and this week, could touch base on Wednesday (any time), Thursday afternoon, any evening after 7pm, or over the weekend (I'm based in San Francisco, so all times PST). You can feel free to reach me at katedelr@uw.edu. Thank you!

**Comment by nniiicc** [comment]
Update 11.14.2018- K to send Nic ~ 2 paragraph description of project for capstone proposal due 12/10.
